name: together_for_you
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.2
  connectivity_plus: ^6.0.3
  device_preview: ^1.1.0
  dot_navigation_bar: ^1.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.1.0
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  intl: 0.18.1
  popover: ^0.3.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
